version: '2'
services:
  postgres:
      image: postgres:9.6
      environment:
          - POSTGRES_USER=airflow
          - POSTGRES_PASSWORD=airflow
          - POSTGRES_DB=airflow
      ports:
          - 5432:5432
  webserver:
      image: puckel/docker-airflow:1.8.0
      restart: always
      depends_on:
          - postgres
      environment:
          - LOAD_EX=n
          - EXECUTOR=Local
      volumes:
          - ./dags:/usr/local/airflow/dags
          - ./plugins:/usr/local/airflow/plugins
          - ./templates:/usr/local/airflow/templates
          - ./requirements.txt:/requirements.txt
      ports:
          - 8080:8080
      command: webserver